__package_name__ = "juno_mapping"
__authors__ = "Boas van der Putten"
__email__ = "ids-bioinformatics@rivm.nl"
__license__ = "AGPLv3"
__version__ = "0.2.1"
__description__ = "Juno-mapping pipeline for reference mapping of bacterial genomes"
