# Source: https://github.com/ewels/MultiQC/blob/master/multiqc_config_example.yaml
# Date: 20181026

# Title to use for the report.
title: Quality control metrics

# How to plot graphs. Different templates can override these settings, but
# the default template can use interactive plots (Javascript using HighCharts)
# or flat plots (images, using MatPlotLib). With interactive plots, the report
# can prevent automatically rendering all graphs if there are lots of samples
# to prevent the browser being locked up when the report opens.
plots_force_flat: False          # Try to use only flat image graphs
plots_force_interactive: False   # Try to use only interactive javascript graphs
plots_flat_numseries: 100        # If neither of the above, use flat if > this number of datasets
num_datasets_plot_limit: 30      # If interactive, don't plot on load if > this number of datasets
max_table_rows: 750             # Swap tables for a beeswarm plot above this

extra_fn_clean_trim:
  - "_bracken_species.kreport2"
  - "_fastp.json"

picard_config:
  general_stats_target_coverage:
    - 10
    - 30
    - 50
    - 100

bcftools:
  collapse_complementary_changes: true

remove_sections:
  - bcftools-stats_variant_quality_plot

custom_plot_config:
  bcftools_stats_indel-lengths:
    xmin: 0

show_hide_buttons:
  - Show only read files
  - Hide all read files
show_hide_mode:
  - show
  - hide
show_hide_patterns:
  - ['_1', '_2', '_pR1', '_pR2']
  - ['_1', '_2', '_pR1', '_pR2']