threads:
    fastp: 4
    fastqc: 1
    bwa: 8
    picard: 1
    gatk: 2
    filter_variants: 2
    kraken2: 8
    samtools: 4
    multiqc: 1
    bbtools: 1
    delly: 1
    other: 1

mem_gb:
    fastp: 8
    fastqc: 4
    bwa: 32
    picard: 64
    gatk: 32
    filter_variants: 8
    kraken2: 64
    samtools: 8
    multiqc: 32
    bbtools: 128
    delly: 16
    other: 8
