# Testing for pipeline python wrapper and scripts used inside rules

name: Conda e2e test

on:
  workflow_dispatch:
  pull_request:

env:
  KRAKEN_DEFAULT_DB: /home/runner/kraken-database

jobs:
  conda_end_to_end:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {os: ubuntu-latest}
    name: Conda Juno_mapping pipeline ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.7
      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          cache-downloads: true
          environment-file: envs/juno_mapping.yaml
      - name: Cache minikraken
        id: cache-minikraken
        uses: actions/cache@v3
        with:
          path: ${{ env.KRAKEN_DEFAULT_DB }}
          key: minikraken-${{ runner.os }}
      - name: Download k2 database
        if: steps.cache-minikraken.outputs.cache-hit != 'true'
        run: |
          mkdir -pv ${{ env.KRAKEN_DEFAULT_DB }}
          cd ${{ env.KRAKEN_DEFAULT_DB }}
          curl -k https://genome-idx.s3.amazonaws.com/kraken/k2_viral_20220908.tar.gz > k2_viral_20220908.tar.gz
          tar zxvf k2_viral_20220908.tar.gz
          ls -lh
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Test juno_mapping pipeline using conda.
        shell: bash -l {0}
        run: pytest -v tests/test_pipeline_conda.py